### ISSUE TITLE
Add sendConfirmationBlocks( ) to Bank and CV

### ISSUE THREAD

**Issue by tomijaga** [thenewboston-developers/thenewboston-js#107]
# Add sendConfirmationBlocks( ) to Bank and CV 

Contributors are able to complete this task and earn thenewboston coins.  Check out the labels to learn how much you can earn for contributing by completing this task.  Please make sure to be honest if you wish to contribute by saying you can't finish this and we can just un-assign you with no harm done!  There is no point in delaying tasks from being completed for miscommunication!

## Overview

Add confirmation block POST request to the `Bank` and `ConfirmationValidator` classes
In the form of a method: `sendConfirmationBlocks( block, account )`

## Behavior
https://thenewboston.com/bank-api/confirmation-blocks

**Comment by tomijaga** [comment]
I'll work on this.

**Comment by zinoadidi** [comment]
@tomijaga this closes as well?

**Comment by tomijaga** [comment]
@zinoadidi Yh this should be closed.
The bounty should be counted as research and not for a PR
