### ISSUE TITLE
[Task] useAddress in Account Manager uses JS SDK

### ISSUE THREAD

**Issue by zinoadidi** [thenewboston-developers/thenewboston-js#111]
# Task

Contributors are able to complete this task and earn thenewboston coins.  Check out the labels to learn how much you can earn for contributing by completing this task.  Please make sure to be honest if you wish to contribute by saying you can't finish this and we can just un-assign you with no harm done!  There is no point in delaying tasks from being completed for miscommunication!

## Overview

generateAccount function in Account manager uses JS SDK

All missing functionalities that hinder the implementation are reported and resolved on the SDK side
Use the SDK documentation
Undocumented processes and wrong information in doc should be corrected
Resolves thenewboston-developers/Account-Manager#585

## Behavior
Account manager uses js sdk installed from NPM https://www.npmjs.com/package/thenewboston
useAddress function in Account manager uses JS SDK

#### Remember to include your account number in your PR description for us to pay you 💰

** Pull Requests **
All Pull Request should be made to development branch, read contributors guild for more information about contributing

**Comment by zinoadidi** [comment]
@tomijaga how about this one

**Comment by zinoadidi** [comment]
@tomijaga can you make a PR from the sdk branch to master and tag justin / me on it;
don't want to claim your fixes :)

**Comment by tomijaga** [comment]
Sure I will do that in a bit

**Comment by tomijaga** [comment]
This was also an error. It had nothing to do with the api.

**Comment by zinoadidi** [comment]
not implemented
