### ISSUE TITLE
Get single nodes from bank and validator class

### ISSUE THREAD

**Issue by tomijaga** [thenewboston-developers/thenewboston-js#121]
# Task

Contributors are able to complete this task and earn thenewboston coins.  Check out the labels to learn how much you can earn for contributing by completing this task.  Please make sure to be honest if you wish to contribute by saying you can't finish this and we can just un-assign you with no harm done!  There is no point in delaying tasks from being completed for miscommunication!

## Overview

Get single nodes from bank and validator class
- getValidator 
- getBank

## Behavior

Methods should return a single record of the node or account requested

#### Remember to include your account number in your PR description for us to pay you 💰

** Pull Requests **
All Pull Request should be made to development branch, read contributors guild for more information about contributing

**Comment by tomijaga** [comment]
Will complete this once this is merged https://github.com/thenewboston-developers/thenewboston-js/pull/120

**Comment by sisco0** [comment]
Hello @tomijaga. Should these methods return the first result in the pagination `results` array, or should a query be accomplished using `account_number`, `node_identifier` or any other field for filtering and getting the first result?

**Comment by tomijaga** [comment]
@sisco0 The API uses a `node_identifier` param to get a single node
You can view the documentation here: https://thenewboston.com/bank-api/validators

Edit: I removed the getAccount method because the Api doesn't support it
