### ISSUE TITLE
[Task] Documentation link in readme should be full url to  github

### ISSUE THREAD

**Issue by zinoadidi** [thenewboston-developers/thenewboston-js#122]
**Describe the bug**

when package is deployed to npm (https://www.npmjs.com/package/thenewboston), under documentation section, if the user clicks the link to documentation, it takes them to a page that doesn't exist

**To Reproduce**
![image](https://user-images.githubusercontent.com/30411401/113421750-4d0d5000-93d4-11eb-803e-2eec4b31404e.png)
![image](https://user-images.githubusercontent.com/30411401/113421815-5eeef300-93d4-11eb-86de-e1bc148db00f.png)
![image](https://user-images.githubusercontent.com/30411401/113421843-69a98800-93d4-11eb-964e-964a7c4328f8.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/30411401/113421884-7cbc5800-93d4-11eb-9cde-7cee669d5ee1.png)

**Screenshots**

**Desktop (please complete the following information):**
 - Browser 

**Smartphone (please complete the following information):**
 - Browser
 - 
**Additional context**
changes should be done in readme.md

** Pull Requests **
All Pull Request should be made against development branch read contributors guide for more information about contributing

**Comment by Samueloyeks** [comment]
I will work on this
