### ISSUE TITLE
[Task] Restructure Readme File, Move contribution guide to new MD file

### ISSUE THREAD

**Issue by zinoadidi** [thenewboston-developers/thenewboston-js#123]
# Task

Contributors are able to complete this task and earn thenewboston coins.  Check out the labels to learn how much you can earn for contributing by completing this task.  Please make sure to be honest if you wish to contribute by saying you can't finish this and we can just un-assign you with no harm done!  There is no point in delaying tasks from being completed for miscommunication!

## Overview

In readme, only one tap should be a focus on contribution and the tab should include a link to the CONTRIBUTING.md file. 
At the moment, the content of this file can be all contribution related content removed from readme like setting up a project for contribution and etc currently in the readme.
Example contributors guide / structure can be found here https://github.com/github/docs/blob/main/CONTRIBUTING.md

## Behavior
- new file is created and included in the repo `CONTRIBUTING.md`  
- content in readme relating to contribution is moved

#### Remember to include your account number in your PR description for us to pay you 💰

** Pull Requests **
All Pull Request should be made to the development branch, read contributors, guide, for more information about contributing

**Comment by Samueloyeks** [comment]
I will work on this
