### ISSUE TITLE
[Task] Add templates for pull requests

### ISSUE THREAD

**Issue by zinoadidi** [thenewboston-developers/thenewboston-js#132]
# Task

Contributors are able to complete this task and earn thenewboston coins.  Check out the labels to learn how much you can earn for contributing by completing this task.  Please make sure to be honest if you wish to contribute by saying you can't finish this and we can just un-assign you with no harm done!  There is no point in delaying tasks from being completed for miscommunication!

## Overview

pull request templates are available to choose from during PR creation

## Behavior
new folder containing pull request templates for popular PR options is  included 

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

```ts
/* template topic examples */

feat, fix, chore, docs, refactor, test 
```

#### Remember to include your account number in your PR description for us to pay you 💰

** Pull Requests **
All Pull Request should be made to development branch, read contributors guild for more information about contributing

**Comment by Samueloyeks** [comment]
I will work on this

**Comment by zinoadidi** [comment]
@Samueloyeks your tnbc account number
