### ISSUE TITLE
[Task] Implement Update Account Method for `Bank`

### ISSUE THREAD

**Issue by sno2** [thenewboston-developers/thenewboston-js#14]
# Task

Contributors are able to complete this task and earn thenewboston coins.  Check out the labels to learn how much you can earn for contributing by completing this task.  Please make sure to be honest if you wish to contribute by saying you can't finish this and we can just un-assign you with no harm done!  There is no point in delaying tasks from being completed for miscommunication!

## Overview

Implement `/accounts/<account_number>` bank server endpoint for `Bank` class.  Please refer to the [docs on this endpoint](https://thenewboston.com/bank-api/accounts).

## Behavior

The method should be called `updateAccount` and it should take in the account number, trust, and a node identifier `Account` class.  The method should generate the PATCH request using the [`patchData` method](https://github.com/thenewboston-developers/thenewboston-js/blob/master/src/server-node.ts#L55-L63).  You must create the message and sign it using the [`Account.createSignedMessage` method](https://github.com/thenewboston-developers/thenewboston-js/blob/master/src/account.ts#L74-L86).  Here is what the shape of the method should look like:

```ts
/**
   * Updates the given server account's trust on the bank.
   * @param accountNumber the account number of the server to update
   * @param trust the trust of the the server
   * @param serverAccount the account for the server node in which the account number is the node identifier and the signing key is the node identifier signing key
   */
async updateAccount(accountNumber: string, trust: number, serverAccount: Account) {
  /* do stuff */
}
```

Please remember to include the JSDoc and good luck!

**Comment by AbhayAysola** [comment]
Hi, can try to complete this?

**Comment by sno2** [comment]
> Hi, can try to complete this?

Sure, please don't be afraid to send a message if you are having any problems!  Thanks
