### ISSUE TITLE
[Task] Rest of Bank functionality in account manager uses JS SDK

### ISSUE THREAD

**Issue by zinoadidi** [thenewboston-developers/thenewboston-js#142]
# Task

Contributors are able to complete this task and earn thenewboston coins.  Check out the labels to learn how much you can earn for contributing by completing this task.  Please make sure to be honest if you wish to contribute by saying you can't finish this and we can just un-assign you with no harm done!  There is no point in delaying tasks from being completed for miscommunication!

## Overview

fetchBankBankTransactions | src/renderer/dispatchers/banks.ts | Gets all the bank transactions for the specified bank
-- | -- | --
fetchBankBlocks | src/renderer/dispatchers/banks.ts | Gets all the blocks for the specified bank
fetchBankConfirmationBlocks | src/renderer/dispatchers/banks.ts | Gets all the banks confirmation blocks
fetchBankInvalidBlocks | src/renderer/dispatchers/banks.ts | Gets all the Invalid blocks for a specified bank
fetchBankValidatorConfirmationServices | src/renderer/dispatchers/banks.ts | Gets all the confirmations blocks for a specified banks blocks

## Behavior

Account manager uses js sdk installed from NPM https://www.npmjs.com/package/thenewboston
Rest of Bank functionality in Account manager uses JS SDK

```ts
/* code examples are awesome */
```

#### Remember to include your account number in your PR description for us to pay you 💰

** Pull Requests **
All Pull Request should be made to development branch, read contributors guild for more information about contributing

**Comment by tomijaga** [comment]
@zinoadidi I've added all of these methods

**Comment by zinoadidi** [comment]
@tomijaga for the sake of bureaucracy :) 
Lets tag the respective PR so i can get Justin to review / close the tasks from this side

**Comment by zinoadidi** [comment]
closed by https://github.com/thenewboston-developers/Account-Manager/pull/610
