### ISSUE TITLE
Verify signature function (code | test | docs)

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/thenewboston-js#163]
Create a function to verify a signature when given a message, signature, and account number. It will be the same logic as this function, just in JS instead of Python.

https://github.com/thenewboston-developers/thenewboston-python/blob/development/src/thenewboston/blocks/signatures.py#L10

**Comment by tomijaga** [comment]
I'll work on this

**Comment by tomijaga** [comment]
We can have the verify function as a static method for the `Account` class

**Comment by zinoadidi** [comment]
@tomijaga assigned

**Comment by tomijaga** [comment]
@zinoadid I submitted a PR
