### ISSUE TITLE
[Task] Create `Bank` Documentation

### ISSUE THREAD

**Issue by sno2** [thenewboston-developers/thenewboston-js#24]
# Task

Contributors are able to complete this task and earn thenewboston coins.  Check out the labels to learn how much you can earn for contributing by completing this task.  Please make sure to be honest if you wish to contribute by saying you can't finish this and we can just un-assign you with no harm done!  There is no point in delaying tasks from being completed for miscommunication!

## Overview

Create a simple and easily-understandable documentation for the `Bank` class.

**Comment by AbhayAysola** [comment]
Can I try working on this one? I'll let you know if I run into any problems.

**Comment by sno2** [comment]
> Can I try working on this one? I'll let you know if I run into any problems.

Yes, please lmk if you have any issues and I can help you write things up.  Also, if you want to create a WIP PR for each of the sections then I could review each of them as soon as I can.

**Comment by sno2** [comment]
@AbhayAysola  You can also check out the [`Account` docs](https://github.com/thenewboston-developers/thenewboston-js/blob/master/docs.md#account) I made today as a reference for the style.

**Comment by AbhayAysola** [comment]
Sure! Thanks for the suggestion, will definitely do that.
