### ISSUE TITLE
[Task] Create `Validator` Documentation

### ISSUE THREAD

**Issue by sno2** [thenewboston-developers/thenewboston-js#25]
# Task

Contributors are able to complete this task and earn thenewboston coins.  Check out the labels to learn how much you can earn for contributing by completing this task.  Please make sure to be honest if you wish to contribute by saying you can't finish this and we can just un-assign you with no harm done!  There is no point in delaying tasks from being completed for miscommunication!

## Overview

Create a simple and easily-understandable documentation for the `Validator` class.

**Comment by CNFloss** [comment]
I'll this a try, this should be interesting.

**Comment by sno2** [comment]
> I'll this a try, this should be interesting.

Great, please don't be afraid to reply in here for any questions or help you need!  Please just put TODO along with the heading for sections that we haven't implemented yet.  Also, it would be great if you could create a WIP pull request and push for each section so we could review it bite-by-bite, but that's optional.

**Comment by CNFloss** [comment]
@sno2 cool yeah I'll definitely push it up in pieces so that I can get feedback!

**Comment by CNFloss** [comment]
@sno2 will the validator class eventually be abstract? I'm just curious because it's probably never going to be created and used on it's own right?  So when writing this up compared to the Account documentation I should keep in mind that I'm just explaining it's functions it gives both types of validators those use cases but explain that a base validator should/could never be created.  Or should I leave it open in case somebody makes a validator for it's functions but never hooks it up to the network?

**Comment by sno2** [comment]
> @sno2 will the validator class eventually be abstract? I'm just curious because it's probably never going to be created and used on it's own right? So when writing this up compared to the Account documentation I should keep in mind that I'm just explaining it's functions it gives both types of validators and those use cases but explain that a base validator should/could never be created. Or should I leave it open in case somebody makes a validator for it's functions but never hooks it up to the network?

Yeah, it should be abstract.  I was thinking that we could, however, have a section for the `Validator` for all of the methods that are the same for both validators (along with a notice that they work for both).  Then, we could have separate sections for the other validators.

**Comment by CNFloss** [comment]
@sno2 I'm actually having trouble finding a valid block id to show the examples and expected output.  My confirmation validator hasn't had done any confirmation services so a URL with a confirmation validator that has some blocks would be cool too.

**Comment by sno2** [comment]
> @sno2 I'm actually having trouble finding a valid block id to show the examples and expected output. My confirmation validator hasn't had done any confirmation services so a URL with a confirmation validator that has some blocks would be cool too.

Hey, sorry for not replying sooner.  I have exams and essays to finish for the final week of school 😔  Anyways, you should be able to use the [example on the endpoint for the docs here](https://thenewboston.com/primary-validator-api/confirmation-blocks).

**Comment by sno2** [comment]
Forgot to close as I had to relink the PR.
