### ISSUE TITLE
[Task] Create `PrimaryValidator` Documentation

### ISSUE THREAD

**Issue by sno2** [thenewboston-developers/thenewboston-js#27]
# Task

Contributors are able to complete this task and earn thenewboston coins.  Check out the labels to learn how much you can earn for contributing by completing this task.  Please make sure to be honest if you wish to contribute by saying you can't finish this and we can just un-assign you with no harm done!  There is no point in delaying tasks from being completed for miscommunication!

## Overview

Create a simple and easily-understandable documentation for the `PrimaryValidator` class.

**Comment by leelatanniru** [comment]
Can i work on this?

**Comment by leelatanniru** [comment]
I assinged to myself. I will try to finish this PR before 21st december. Thank you.

**Comment by AbhayAysola** [comment]
Hey, @leelatanniru are you working on this?

**Comment by leelatanniru** [comment]
No @AbhayAysola

**Comment by AbhayAysola** [comment]
If that's the case, @sno2 can I work on this?

**Comment by sno2** [comment]
> If that's the case, @sno2 can I work on this?

Yes, just assigned it to you.  Thanks

**Comment by AbhayAysola** [comment]
Sorry, I didn't see that till now. I will work on it. 👍🏼

**Comment by AbhayAysola** [comment]
So I just looked into it, and there's only one method - `addBankBlocks`. Is this the only method I need to document?

**Comment by sno2** [comment]
> So I just looked into it, and there's only one method - `addBankBlocks`. Is this the only method I need to document?

Yep
