### ISSUE TITLE
[Task] Implement POST Update Notice Method for `Bank`

### ISSUE THREAD

**Issue by sno2** [thenewboston-developers/thenewboston-js#28]
# Task

Contributors are able to complete this task and earn thenewboston coins.  Check out the labels to learn how much you can earn for contributing by completing this task.  Please make sure to be honest if you wish to contribute by saying you can't finish this and we can just un-assign you with no harm done!  There is no point in delaying tasks from being completed for miscommunication!

## Overview

Implement the POST `/upgrade_notice` endpoint as a `Bank` method.  This method should take in the `nodeIdentifier` of the bank server that is supposed to be receiving the upgrade notice.   Refer the [docs on the `/upgrade_notice` endpoint](https://thenewboston.com/bank-api/upgrade-notice) and the [`Bank.updateAccount` method](https://github.com/thenewboston-developers/thenewboston-js/blob/master/src/bank.ts#L15-L23) (of course use `postData` instead of `patchData`).

## Behavior

Here is the shape of the `sendUpgradeNotice` method within the `Bank` class:

```ts
class Bank {
  /**
   * Sends a signed POST request to the bank for an upgrade notice.
   * @param nodeIdentifier the node identifier of the bank that is receiving the upgrade notice
   * @param bankAccount the current bank server's account
   */
  async sendUpgradeNotice(nodeIdentifier: string, bankAccount: Account): Promise<any>
}
```

Note: make sure to include the JSDoc in your code.

**Comment by CNFloss** [comment]
I give this one a shot!

**Comment by sno2** [comment]
> I give this one a shot!

Great
