### ISSUE TITLE
[Task] Type `PrimaryValidator.getConfig` Method Response

### ISSUE THREAD

**Issue by sno2** [thenewboston-developers/thenewboston-js#36]
# Task

Contributors are able to complete this task and earn thenewboston coins.  Check out the labels to learn how much you can earn for contributing by completing this task.  Please make sure to be honest if you wish to contribute by saying you can't finish this and we can just un-assign you with no harm done!  There is no point in delaying tasks from being completed for miscommunication!

## Overview

Create an interface like the [`BankConfigResponse` interface](https://github.com/thenewboston-developers/thenewboston-js/blob/master/src/models/responses/bank/config.ts#L3-L26) for what the `getConfig` `PrimaryValidator` method will return.  Use the [docs on this endpoint](https://thenewboston.com/primary-validator-api/config) and the [`Bank.getConfig` method](https://github.com/thenewboston-developers/thenewboston-js/blob/master/src/bank.ts#L53-L58) as examples for how to complete this.

**Comment by CNFloss** [comment]
I'll take this one.

**Comment by sno2** [comment]
Thanks @CNFloss , just assigned it to you👍
