### ISSUE TITLE
[Task] Implement `Bank` POST Blocks Method

### ISSUE THREAD

**Issue by sno2** [thenewboston-developers/thenewboston-js#37]
# Task

Contributors are able to complete this task and earn thenewboston coins.  Check out the labels to learn how much you can earn for contributing by completing this task.  Please make sure to be honest if you wish to contribute by saying you can't finish this and we can just un-assign you with no harm done!  There is no point in delaying tasks from being completed for miscommunication!

## Overview

Create a method named `addBlocks` for the `Bank` class which will take in the currently `balanceLock` (`string`), transactions `Transaction[]`, and the `senderAccount` (`Account`).  Refer to the [docs on this endpoint](https://thenewboston.com/bank-api/blocks) and the [`Account` docs on creating block messages](https://github.com/thenewboston-developers/thenewboston-js/blob/master/docs.md#using-block-data-and-block-messages).

## Behavior

This is how the shape of the function should look like:

```ts
class Bank {
  /**
   * Adds new transaction blocks to the blockchain.
   * @param balanceLock the current balance lock
   * @param transactions the transactions to push to the block chain
   * @param account the account that is sending the transactions
   */
  async addBlocks(balanceLock: string, transactions: Transaction[], account: Account) {
    /* code */
  }
}
```

**Comment by nishp77** [comment]
working on it

**Comment by sno2** [comment]
> working on it

Thanks, just assigned it to you 👍
