### ISSUE TITLE
[Task] Implement Bank Blocks Endpoint for Primary Validator

### ISSUE THREAD

**Issue by sno2** [thenewboston-developers/thenewboston-js#47]
# Task

Contributors are able to complete this task and earn thenewboston coins.  Check out the labels to learn how much you can earn for contributing by completing this task.  Please make sure to be honest if you wish to contribute by saying you can't finish this and we can just un-assign you with no harm done!  There is no point in delaying tasks from being completed for miscommunication!

## Overview

Build a `addBankBlocks` method onto the `PrimaryValidator` class that sends a POST request to the `/bank_blocks` endpoint.  Refer to the [docs on this endpoint ](https://thenewboston.com/primary-validator-api/bank-blocks)for more information.

## Behavior

The developer should be able to put in the sender's `Account` object and the transactions to add to the blockchain.  They should also specify the node identifier of the bank that will be taking in the transactions.

```ts
class PrimaryValidator {
  // snip

  async addBankBlocks(bankIdentifier: string, balanceLock: string, transactions: Transaction[], account: Account) {
    /* your code */
  }

  // snip
}

```

**Comment by nishp77** [comment]
Working on it
