### ISSUE TITLE
[Task] Send database synchronisable idempotent payment

### ISSUE THREAD

**Issue by Kycermann** [thenewboston-developers/thenewboston-js#57]
# Task

Contributors are able to complete this task and earn thenewboston coins.  Check out the labels to learn how much you can earn for contributing by completing this task.  Please make sure to be honest if you wish to contribute by saying you can't finish this and we can just un-assign you with no harm done!  There is no point in delaying tasks from being completed for miscommunication!

## Overview

The `PaymentHandler` allows us to easily send TNBC. What if we need to synchronise with a database?

Possible approaches with the existing `PaymentHandler`:
1. First update the database. Then send the money. Oh no, the database was updated but then sending failed because the code crashed or the bank went offline. Now the database thinks money was sent but it wasn't!
2. First send the money. Then update the database. Oh no, we sent the money but the database went offline so now it thinks that we didn't send the money.

Solution:
1. Create the transaction (and this API has to expose the transaction before it's sent)
2. Store the transaction in the database, marked as not sent
3. Broadcast the transaction. If the database goes down or the code fails before the transaction is broadcast, that's fine- we'll just try broadcasting again
4. Now we're 100% sure that step 3 is complete, mark the transaction as complete in the database. If this step fails, we're back at step 3 but that won't ever result in double payment- because the same transaction can't execute twice. Eventually the payment will succeed (or the database will show that the payment wasn't successful)

With this solution, the database state is correct at all points in time- no matter what goes wrong.

## Behavior

The `PaymentHandler` API should expose the abilities to create a transaction and expose the transaction. It should also expose a method to send a transaction (that the `PaymentHandler` created) to the bank.

```ts
const {bank, transaction} = PaymentHandler.createTransaction(account, targetAddress, amount);

// First store transaction and mark payment as sent all in one database transaction (atomically)
// If the next line fails, no payment is recorded as having been sent
await database.storeTransaction(transaction);

// Now we can try to broadcast it
// If the next line fails, that's ok because we can try again later and it won't result in double or missed payments
PaymentHandler.broadcastTransaction(bank, transaction);

// Now we're 100% sure that the transaction was sent
// If the next line fails, we'll end up trying to broadcast again but that's fine, it's the same transaction with each attempt
await database.markTransactionAsSent(transaction);
```

**Comment by AbhayAysola** [comment]
So instead of having one method, `sendCoins` we need to split that up into two methods, `createTransaction` and `broadcastTransaction` ?

**Comment by Kycermann** [comment]
@AbhayAysola yep, this would make it so much easier for users of this library to achieve full database/blockchain consistency

**Comment by AbhayAysola** [comment]
Yup, sounds pretty straightforward. Can I work on this? @Kycermann

**Comment by Kycermann** [comment]
> Yup, sounds pretty straightforward. Can I work on this? @Kycermann 

Sure

**Comment by sno2** [comment]
IMO you should have a `Transaction` class that contains the information on a single transaction (sender account key pairs, receiver account number + amount) that can be held locally, used within `PaymentHandler.sendCoins()`, and still implement the `PaymentHandler.dispatchTransaction` of such.  It matches the OOP vibe, and although it may require another import field, it makes more sense in my eyes to allow transactions without having to deal with the `PaymentHandler.createTransaction` method for account managers, websites, ect.

**Comment by AbhayAysola** [comment]
> IMO you should have a `Transaction` class that contains the information on a single transaction (sender account key pairs, receiver account number + amount) that can be held locally, used within `PaymentHandler.sendCoins()`, and still implement the `PaymentHandler.dispatchTransaction` of such. It matches the OOP vibe, and although it may require another import field, it makes more sense in my eyes to allow transactions without having to deal with the `PaymentHandler.createTransaction` method for account managers, websites, ect.

That makes a lot of sense, I'll work on that now.

**Comment by AbhayAysola** [comment]
Should I make a new file for the `Transaction` class or do it inside the same one? @sno2

**Comment by sno2** [comment]
I'm not on the team anymore, so I dunno who's actually leading the project...

**Comment by AbhayAysola** [comment]
> I'm not on the team anymore, so I dunno who's actually leading the project...

Hmm okay, I'll just wing it then 😅

**Comment by AbhayAysola** [comment]
I added that, let me know if it looks good to you. I'll ask around on Slack to see who is the lead now.

**Comment by mrbusysky** [comment]
Looks good to me.
