### ISSUE TITLE
Any ETA on Documentation?

### ISSUE THREAD

**Issue by mrbusysky** [thenewboston-developers/thenewboston-js#6]
Currently in the process of working on my project proposal. 
It would be nice to have some decent documentation.

**Comment by sno2** [comment]
This library needs to have payment functionality before we should start working on a documentation.

**Comment by zinoadidi** [comment]
Some form of documentation is available https://github.com/thenewboston-developers/thenewboston-js/blob/master/docs/index.md so i am closing this issue. 
If specific functionalities are not yet documented, we can open a new one
