### ISSUE TITLE
[Task] Add "fee" Field in Transactions

### ISSUE THREAD

**Issue by AbhayAysola** [thenewboston-developers/thenewboston-js#61]
# Task

Contributors are able to complete this task and earn thenewboston coins.  Check out the labels to learn how much you can earn for contributing by completing this task.  Please make sure to be honest if you wish to contribute by saying you can't finish this and we can just un-assign you with no harm done!  There is no point in delaying tasks from being completed for miscommunication!

## Overview

The latest version of thenewboston bank uses a new field in transactions called `fee`. This field is used to differentiate normal transactions from transactions which are sent as fees to either banks or validators. 

## Behavior

The task is to add this field to the library as currently it is not possible to send coins using this library.

**Comment by zinoadidi** [comment]
looks good;
Future contributions to be made through the development branch
