### ISSUE TITLE
[Task] [Priority] Fix automatic deployments

### ISSUE THREAD

**Issue by Kycermann** [thenewboston-developers/thenewboston-js#65]
# Task

Contributors are able to complete this task and earn thenewboston coins.  Check out the labels to learn how much you can earn for contributing by completing this task.  Please make sure to be honest if you wish to contribute by saying you can't finish this and we can just un-assign you with no harm done!  There is no point in delaying tasks from being completed for miscommunication!

## Overview

The lint command is missing in package.json. This needs fixing so that the package deploys to npm. Also we **must** make sure that PRs don't break deployments before merging!

<img width="193" alt="image" src="https://user-images.githubusercontent.com/59399685/110106242-57bad200-7da1-11eb-8e8a-7c0837f80d19.png">

This issue is resolved when there's a green tick in area screenshotted above.

**Comment by Kycermann** [comment]
@AbhayAysola perhaps you'd like to work on this? Otherwise I'm happy to pick this up.
@zinoadidi could you assign a reward please? This is a tiny but important task.

**Comment by AbhayAysola** [comment]
> @AbhayAysola perhaps you'd like to work on this? Otherwise I'm happy to pick this up.
That's alright, you can go ahead 👍🏼

**Comment by zinoadidi** [comment]
sadly already fixed this one.
There are other issues as well with the deployment process; fixing them.

But there are lot more issues, I will create some tasks soon so you guys can help

**Comment by zinoadidi** [comment]
Issues with deployment fixed here #66

**Comment by Kycermann** [comment]
@zinoadidi Thank you so much. You're actually the best <3

**Comment by Kycermann** [comment]
@zinoadidi Ahh when I do `npm install`- there's still no `dist` folder so the module doesn't work without going inside of it and doing `npm install && npm run build`.

**Comment by Kycermann** [comment]
We ended up placing this in issue #69.
