### ISSUE TITLE
[Task] Create ESLint file and get existing codebase to comform to eslint rules specified

### ISSUE THREAD

**Issue by zinoadidi** [thenewboston-developers/thenewboston-js#68]
# Task

Contributors are able to complete this task and earn thenewboston coins.  Check out the labels to learn how much you can earn for contributing by completing this task.  Please make sure to be honest if you wish to contribute by saying you can't finish this and we can just un-assign you with no harm done!  There is no point in delaying tasks from being completed for miscommunication!

## Overview

We need to include eslint file to the project with rules derived based on the current project/code setup. Changes should be backward compatible i.e should not break third-party usage of the library and existing interfaces.

## Behavior

Eslint file is present with standard rules and when `npm run lint` all rules should pass.

```ts
![image](https://user-images.githubusercontent.com/30411401/110109226-cefa6100-7db5-11eb-920a-70e0e7f6c72c.png)

```

**Comment by jamessspanggg** [comment]
@zinoadidi should this be closed?

**Comment by Ayah206** [comment]
May I get assigned to this task?
