### ISSUE TITLE
[Task] Fix npm deployments (extra 2000 TNBC bounty available)

### ISSUE THREAD

**Issue by Kycermann** [thenewboston-developers/thenewboston-js#69]
# Task

Contributors are able to complete this task and earn thenewboston coins.  Check out the labels to learn how much you can earn for contributing by completing this task.  Please make sure to be honest if you wish to contribute by saying you can't finish this and we can just un-assign you with no harm done!  There is no point in delaying tasks from being completed for miscommunication!

## Overview

When you run `npm install thenewboston`, there's no `dist` directory. You can't then just `require("thenewboston")` without going inside `node_modules/thenewboston` and running `npm install && npm run build` first.

If you `require("thenewboston")` without going inside the module and running `npm install && npm run build` first, you get an error:

```
node:internal/modules/cjs/loader:352
      throw err;
      ^

Error: Cannot find module '/Users/mieszkokycermann/Desktop/Projects/Mieszko-Exchange/Crypto-API/node_modules/thenewboston/dist/index.js'. Please verify that the package.json
 has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:344:19)
    at Function.Module._findPath (node:internal/modules/cjs/loader:557:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:911:27)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/mieszkokycermann/Desktop/Projects/Mieszko-Exchange/Crypto-API/src/crypto/impl/tnb.js:4:55)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/Users/mieszkokycermann/Desktop/Projects/Mieszko-Exchange/Crypto-API/node_modules/thenewboston/package.json',
  requestPath: 'thenewboston'
}
```

When you `npm install` in your project root, the TNB module resets and you have to manually go in and set it up again.

## Behavior

This task is complete when you can do `npm install thenewboston` and that installs with the `dist` directory already there (preferably deploy that directory to npm for faster installs but a pre-install script works too if that's a thing).

**Comment by Kycermann** [comment]
If this is closed in the next 24 hours, I will personally pay an additional bounty of 2000 TNBC.

**Comment by zinoadidi** [comment]
Would be nice if all issues identified that are not yet resolved concerning deployment are fixed through this issue.
Also don't forget, PR to development branch so we can have some sort of controlled deployment in future

**Comment by AbhayAysola** [comment]
I was thinking we could do a releases workflow first and then do `npm publish` with the release assets. Would be simpler in the future if we are planning to add releases. If releases are not planned then we can go with the normal method. @zinoadidi @Kycermann

**Comment by Kycermann** [comment]
@AbhayAysola whatever works long term is fine. I like the workflow idea. Maybe run build on GitHub actions and publish that.

**Comment by AbhayAysola** [comment]
> @AbhayAysola whatever works long term is fine. I like the workflow idea. Maybe run build on GitHub actions and publish that.

I meant using [Github Releases](https://docs.github.com/en/github/administering-a-repository/about-releases). It's up to the repo maintainer to decide whether we have Releases or not.
