### ISSUE TITLE
[Task] Investigate existing classes and tests, fix broken tests if any (npm run test command should work locally and on github actions)

### ISSUE THREAD

**Issue by zinoadidi** [thenewboston-developers/thenewboston-js#72]
# Task

Contributors are able to complete this task and earn thenewboston coins.  Check out the labels to learn how much you can earn for contributing by completing this task.  Please make sure to be honest if you wish to contribute by saying you can't finish this and we can just un-assign you with no harm done!  There is no point in delaying tasks from being completed for miscommunication!

## Overview

Fix broken/outdated tests and submit a PR with all tests passing; in addition, the npm test command should work locally and on GitHub actions

## Behavior

All working tests in PR, if any tests are broken or outdated, should be fixed and included.
the npm run test command should work locally and on GitHub actions

**Comment by Musabii** [comment]
Can i take this one?

**Comment by zinoadidi** [comment]
yes @Musabii assigned

**Comment by Musabii** [comment]
sorry i gave it a try but i think it's way ahead of my current skills so i'll unassign myself

**Comment by denistsoi** [comment]
i can try to ahve a look at this but 

tried a week ago - 
the issue for anyone attempting this task is that the SDK is connecting to a node and 
you'll have to mock the implementation of that.

It doesn't necessarily make sense to mock the implementation via new `Bank/PrimaryValidator/ConfirmationValidator/PaymentValidator` as the 

I feel that the sdk will eventually have to be updated with the `beta` update as well.

just fyi - feel this isn't as straight-forward/easily accessible

**Comment by zinoadidi** [comment]
@denistsoi lets see what you can do with it; One option will be to exclude it from tests but if its possible to mock something without defeating the purpose; lets try it out

**Comment by dras51** [comment]
I believe this issue has been fixed and should be closed. ran tests locally and they all passed. [HERE](https://github.com/thenewboston-developers/thenewboston-js/runs/2250163517?check_suite_focus=true) is a link that shows the last github action that shows the tests are passing.

**Comment by zinoadidi** [comment]
Task investigated by @dras51 and investigation results are provided

**Comment by tomijaga** [comment]
I think @AbhayAysola was the one that fixed and added most of the tests.

**Comment by zinoadidi** [comment]
@tomijaga thanks for clarifying. I was also a bit confused when the results came back and were positive :)
