### ISSUE TITLE
[Task] Investigate TNB account manager and submit a report on missing functionalities on TNB-JS that are implemented in account manager

### ISSUE THREAD

**Issue by zinoadidi** [thenewboston-developers/thenewboston-js#73]
# Task

Contributors are able to complete this task and earn thenewboston coins.  Check out the labels to learn how much you can earn for contributing by completing this task.  Please make sure to be honest if you wish to contribute by saying you can't finish this and we can just un-assign you with no harm done!  There is no point in delaying tasks from being completed for miscommunication!

## Overview

tnb js library should be the single source of truth for all JS integration, in order to bring it up to speed, there is a need to understand what functionalities are missing from the library. 
The most updated source to verify functionalities is the account manager (thenewboston-developers/Account-Manager)

The task involves going through the account manager code to identify what functionalities are implemented there and are missing from tnb-js library. 
Once you have a comprehensive list of features that need to be implemented on our side, submit a comment / .MD file / google docs here for discussion

## Behavior
A report of the missing functionalities in the js library that are present in the account manager, and the reference link to the respective file where the functionality (JS/TS) is implemented in the account manager.  

Since the task is large, I suggest splitting between two people who indicate interest and are assigned to it so everyone knows who is working on it. Bounty will be shared between both persons.

**Comment by tomijaga** [comment]
Can I work on this?

**Comment by zinoadidi** [comment]
yes, assigned @tomijaga ;
One more person can still join :)

**Comment by Ayah206** [comment]
can I get assigned to this?

**Comment by zinoadidi** [comment]
@Ayah206 done;
Find @tomijaga and agree how to share work or what you could do to speed up work

**Comment by tomijaga** [comment]
Welcome @Ayah206! 

Most of the functions in the account manager repo for thenewboston network and nodes are in the [src/renderer](https://www.github.com/thenewboston-developers/Account-Manager/tree/master/src%2Frenderer) directory.

Specifically in: 
`config`
`constants`
`containers`
`dispatchers`
`hooks`
`utils`

I will be working on the last 3, you can help with the top 3. 

I recommend documenting the common functionality between the account manager and thenewboston-js so it will be easier to identify the ones that are missing

I will post a shared word document so that we can monitor our progress

**Comment by Ayah206** [comment]
Okay, Thank you. I will start working on the specified documents right away

**Comment by tomijaga** [comment]
@Ayah206 Here's the word doc
https://docs.google.com/document/d/1FaPq2stWP0lMtHATNIfLA6ryMd0PtUYdcnrvZbUk7FI/edit?usp=sharing

**Comment by Ayah206** [comment]
@tomijaga, seen. I will update my progress soon

**Comment by tomijaga** [comment]
@zinoadidi what do you think of the format

**Comment by zinoadidi** [comment]
Hello @tomijaga, it looks good!.
I am eager to see what comes from @Ayah206 as it seems there are not that many things left to implement based on the information i see. 
To speed up the process of integrating tnb js and account manager (https://github.com/thenewboston-developers/Account-Manager/issues/585) I think once you guys finalize your work and all tests are done from our side, someone can already start with account integrations.

But yea; most important right now is seeing what other stones are unturned.
@Ayah206 What is the likely timeline for us to get your own side of the task or are you having any difficulties completing it?

Also, to clarify; all API requests/interaction with the banks, pv and etc currently happening on the account manager needs to go through the JS library. Then it will be full solution that tnb js acts like a middle man between FE and Network

**Comment by Ayah206** [comment]
Hello, @zinoadidi  and @tomijaga. I'm sorry, I haven't really been active on the task this past week due to my health condition. I've resumed working on it again and will update  my results as soon as I can

**Comment by zinoadidi** [comment]
Hello, just checking again with you @Ayah206, how is it going now; are you having some difficulties still or things are a bit smooth

**Comment by Ayah206** [comment]
> Hello, just checking again with you @Ayah206, how is it going now; are you having some difficulties still or things are a bit smooth

Yes please, having a bit of challenge with my schedule right now. I think it will be for the best to have someone else fill in on my tasks, instaed of leaving it hanging. So sorry for the delay 😐

**Comment by tomijaga** [comment]
I'll finish up the remaining tasks

**Comment by tomijaga** [comment]
@zinoadidi I am done with this. I've covered all the API requests. The only addition i made was for bulk payments

**Comment by tomijaga** [comment]
Once this is approved I can start switching all the **GET** request functions on the account manager to the methods on **thenewboston-js** repos

**Comment by zinoadidi** [comment]
@tomijaga good job!
I am working with Justin to establish a clear roadmap going forward. 
Once this is done, I will give feedback for all pending tasks.

In the meantime, can you look into this? its also needed that all classes are tested before we start switching https://github.com/thenewboston-developers/thenewboston-js/issues/75
you can prepare a document instead of creating the tasks if it's too much work.

A little disclaimer is payments are still frozen and I don't have the correct answers to what happens to already existing bounties before the freeze.

**Comment by zinoadidi** [comment]
@tomijaga I will create tasks for those missing parts to be implemented class by class;
Would you like to do those missing parts first then proceed with migrating the account manager or how do you want to proceed

**Comment by zinoadidi** [comment]
At the moment there are two main blockers

- Missing tests
- Missing functionality implementation (feature, doc, test) 

Once those two are out of the way; i can give a go-ahead for implementation on account manager side

**Comment by tomijaga** [comment]
@zinoadidi Sure, I could do the missing parts. I just need some more information on the best way to implement them

**Comment by zinoadidi** [comment]
tasks have been created for all identified functionalities.

**Comment by zinoadidi** [comment]
@tomijaga  kindly comment account number below

**Comment by tomijaga** [comment]
@zinoadidi
8de30226230c35bbc1ce4a63c62a7b9c86bf0ce21fc7bc1a984b7884a9f88782
