### ISSUE TITLE
[Task]  Find a not yet tested class or list of function in an already tested class that is not yet tested in thenewboston-js project (bug bounty paid per issue reported)

### ISSUE THREAD

**Issue by zinoadidi** [thenewboston-developers/thenewboston-js#75]
# Task

Contributors are able to complete this task and earn thenewboston coins.  Check out the labels to learn how much you can earn for contributing by completing this task.  Please make sure to be honest if you wish to contribute by saying you can't finish this and we can just un-assign you with no harm done!  There is no point in delaying tasks from being completed for miscommunication!

## Overview

Some classes and methods in thenewboston-js library are missing tests (Unit tests). To earn TNBC, find a not tested class or list of function in an already tested class that is not yet tested in thenewboston-js repository and report an issue following the format here https://github.com/thenewboston-developers/Website/issues/1357
Once you create an issue that complies with information here and it is not duplicate, the bounty will be assigned (250 tnbc) for each task created
Link the task you created via commenting on this issue, the URL of the task
Note: Please try not to create duplicates

## Behavior
- Each issue should be specific to a class; 
- All untested methods in class to be listed in issue;
- Find test samples from existing tests and include links to the sample file.

**Comment by dras51** [comment]
I will work on this

**Comment by zinoadidi** [comment]
@dras51 any updates about this?

**Comment by dras51** [comment]
#153
