### ISSUE TITLE
Create Payment Handler Docs

### ISSUE THREAD

**Issue by tomijaga** [thenewboston-developers/thenewboston-js#80]
# Create Payment Handler Docs 

Contributors are able to complete this task and earn thenewboston coins.  Check out the labels to learn how much you can earn for contributing by completing this task.  Please make sure to be honest if you wish to contribute by saying you can't finish this and we can just un-assign you with no harm done!  There is no point in delaying tasks from being completed for miscommunication!

## Overview

Create a simple and easily-understandable documentation for the `PaymentHandler` class.

**Comment by zinoadidi** [comment]
Hi @tomijaga you can start work on this but to be clear, I do not have visible information concerning bounties yet and how this will unfold in the coming days.

This repo may or may not get bounties in the coming week; it solely depends on the final decision that comes from tnb government

I will keep it open until there is a final decision on what happens next.

**Comment by tomijaga** [comment]
Most of the methods in the `PaymentHandler` class are only used internally so i only made docs for the `AccountPaymentHandler`

**Comment by zinoadidi** [comment]
Hi @tomijaga, I have some clarity on how things might proceed so we can continue working for now.

**Comment by tomijaga** [comment]
@zinoadidi is thenewboston-js moving forward as it's own project it it will be counted as part of frontend on the core team?

**Comment by zinoadidi** [comment]
@tomijaga it will be as a project with slightly different conditions as our work will be closely aligned with  the chain's development. 

Tasks and other activities will remain, just some added berocracy like submitting the milestones with set of tasks in them for funding approval and getting paid after the milestone is complete.

This is as much as I have gone with the discussions but things can still change still waiting for go ahead from the government.

But pretty much all not yet paid / completed tasks will go in our first milestone for clearing once things are fully settled

**Comment by tomijaga** [comment]
Thanks @zinoadidi
