### ISSUE TITLE
[Task] Gets the PV set for a bank (feature | tests | docs)

### ISSUE THREAD

**Issue by zinoadidi** [thenewboston-developers/thenewboston-js#84]
# Task

Contributors are able to complete this task and earn thenewboston coins.  Check out the labels to learn how much you can earn for contributing by completing this task.  Please make sure to be honest if you wish to contribute by saying you can't finish this and we can just un-assign you with no harm done!  There is no point in delaying tasks from being completed for miscommunication!

## Overview

Name of function | Class To add Function | Location in Account Manager | Function Description | Comments
-- | -- | -- | -- | --

getBankPV | Bank | src/renderer/dispatchers/app.ts | Gets the PV set for a bank |  
-- | -- | -- | -- | --

## Behavior
- Resolves: #73 
- user should be able to get the PV set for a bank using the SDK
- changes to existing code should be backward compatible if possible
- tests should be provided for new methods / updated for old ones
- documentation should be provided for new method / updated for old ones

```ts
/* code examples are awesome */
```

**Comment by AbhayAysola** [comment]
Can I work on this?

**Comment by zinoadidi** [comment]
Yes, thanks

**Comment by zinoadidi** [comment]
@tomijaga can you look at the PR attached to this when you have time, thanks
