### ISSUE TITLE
[Task]  Implement `craw` functionality (feature | tests | docs)

### ISSUE THREAD

**Issue by zinoadidi** [thenewboston-developers/thenewboston-js#85]
# Task

Contributors are able to complete this task and earn thenewboston coins.  Check out the labels to learn how much you can earn for contributing by completing this task.  Please make sure to be honest if you wish to contribute by saying you can't finish this and we can just un-assign you with no harm done!  There is no point in delaying tasks from being completed for miscommunication!

## Overview

Name of function | Class To add Function | Location in Account Manager | Function Description | Comments
-- | -- | -- | -- | --

crawl | Confirmation Validator, Bank | src/renderer/hooks/useCrawlSockets.t | browsing nodes in order to discover new ones on the network
-- | -- | -- | --

## Behavior
- Resolves: #73 
- user should be able to browse nodes in order to discover new ones on the network using the SDK
- changes to existing code should be backward compatible if possible
- tests should be provided for new methods / updated for old ones
- documentation should be provided for new method / updated for old ones

```ts
/* code examples are awesome */
```

**Comment by tomijaga** [comment]
I'll work on this @zinoadidi
