### ISSUE TITLE
[Task] Get transaction fee from node (feature | tests | docs) 

### ISSUE THREAD

**Issue by zinoadidi** [thenewboston-developers/thenewboston-js#87]
# Task

Contributors are able to complete this task and earn thenewboston coins.  Check out the labels to learn how much you can earn for contributing by completing this task.  Please make sure to be honest if you wish to contribute by saying you can't finish this and we can just un-assign you with no harm done!  There is no point in delaying tasks from being completed for miscommunication!

## Overview

Name of function | Class To add Function | Location in Account Manager | Function Description | Comments
-- | -- | -- | -- | --

txFee | Primary Validator, Bank | src/renderer/utils/transactions.ts | Returns transaction fee of bank and pv | Currently, the fee details are obtained from the node’s config. It would be better it could be accessed directly from the node
-- | -- | -- | -- | --

## Behavior
- Resolves: #73 
- user should be able to get transaction fee from node using the SDK
- changes to existing code should be backward compatible if possible
- tests should be provided for new methods / updated for old ones
- documentation should be provided for new method / updated for old ones

```ts
/* code examples are awesome */
```

**Comment by AbhayAysola** [comment]
Can I work on this? @zinoadidi

**Comment by AbhayAysola** [comment]
@zinoadidi Should I implement this on the `ServerNode` class or both `PrimaryValidator` and `Bank`. I'm guessing it would be better  on `PrimaryValidator` and `Bank` since even the `ConfirmationValidator` would inherit the method if I do it on the `ServerNode` class.

**Comment by zinoadidi** [comment]
PrimaryValidator and Bank would be the safe option here; 
then it aligns as well with the account manager somewhat
