### ISSUE TITLE
[Task] Implement support for Memo in transactions

### ISSUE THREAD

**Issue by zinoadidi** [thenewboston-developers/thenewboston-js#88]
# Task

Contributors are able to complete this task and earn thenewboston coins.  Check out the labels to learn how much you can earn for contributing by completing this task.  Please make sure to be honest if you wish to contribute by saying you can't finish this and we can just un-assign you with no harm done!  There is no point in delaying tasks from being completed for miscommunication!

## Overview
Based on preliminary information available here https://github.com/thenewboston-developers/Management/issues/81 and implementation in account manager https://github.com/thenewboston-developers/Account-Manager/pull/615
Provide an implementation for the Memo feature for transaction on the chain

## Behavior

Users should be able to use the SDK to create/perform transactions that include a memo/description of the transaction.

an example implementation can be found here https://github.com/thenewboston-developers/Account-Manager/pull/615

**Comment by AbhayAysola** [comment]
I'd like to work on this @zinoadidi

**Comment by zinoadidi** [comment]
@AbhayAysola  any update /  clue with this task yet?
Did you find the person working on it

**Comment by AbhayAysola** [comment]
> @AbhayAysola any update / clue with this task yet?
> Did you find the person working on it

Couldn't find any info, I asked on Discord as well

**Comment by zinoadidi** [comment]
@AbhayAysola here is the implementation https://github.com/thenewboston-developers/Account-Manager/pull/615
