### ISSUE TITLE
Implementing Browser Support with Browserify

### ISSUE THREAD

**Issue by mrbusysky** [thenewboston-developers/thenewboston-js#9]
I'd like to see if we can get this library to work from in browser with no need for a back end.
So besides an npm backend, we could use [Browserify](https://github.com/browserify/browserif) or [Webpack](https://github.com/webpack/webpack) allowing us to decentralize projects right away giving projects the choice of backend or no backend.

webpack / webpack-visualizer-plugin - Might be a good combo

Any thoughts?

**Comment by sno2** [comment]
This is not realistic for us to handle all of the bundling.  We should include the `require` functions within our builds as npm will know what dependencies we are using and download them into the `node_modules`.  We would not only have to include this library's code into this bundle, but every single dependency (and it's dependencies and the dependencies of that one) into this js file.  You can add to the rollup config and add an npm script to build for web, but this will not be the build used by people who are importing our library via `require`.  However, if people did want to just have a js file for the whole library, there are many services that for free do that by just importing the library from a specific url on their domain.

**Comment by mrbusysky** [comment]
Yeah downloading it from the repo might be a good idea this is currently the method used by all chains looking to decentralize the browser. On building the repo it makes a .js or .min.js file that they can just plop in their projects then link to a server in javascript and push transactions from browser.

**Comment by mrbusysky** [comment]
Added browserify https://github.com/thenewboston-developers/thenewboston-js/pull/13

**Comment by sno2** [comment]
@thenewboston-developers/payment-processor-developers Can someone please pay @MrBusySky, thank you very much!
