### ISSUE TITLE
[Task] Test bank class

### ISSUE THREAD

**Issue by zinoadidi** [thenewboston-developers/thenewboston-js#90]
# Task

Contributors are able to complete this task and earn thenewboston coins.  Check out the labels to learn how much you can earn for contributing by completing this task.  Please make sure to be honest if you wish to contribute by saying you can't finish this and we can just un-assign you with no harm done!  There is no point in delaying tasks from being completed for miscommunication!

## Overview
Parent:  https://github.com/thenewboston-developers/thenewboston-js/issues/75
Test bank class in the SDK and methods under the bank class.

## Behavior

All tests you change/add need to be passing tests both locally and in Github Actions

```ts
/* code examples are awesome */
```

**Comment by AbhayAysola** [comment]
I'd like to work on this :)
