### ISSUE TITLE
[Task] Create Primary Validator tests

### ISSUE THREAD

**Issue by zinoadidi** [thenewboston-developers/thenewboston-js#93]
# Task

Contributors are able to complete this task and earn thenewboston coins.  Check out the labels to learn how much you can earn for contributing by completing this task.  Please make sure to be honest if you wish to contribute by saying you can't finish this and we can just un-assign you with no harm done!  There is no point in delaying tasks from being completed for miscommunication!

## Overview
parent: #75
 Primary Validator tests in js sdk

## Behavior

All tests you change/add need to be passing tests both locally and in Github Actions
See Account manager for examples if you get stuck, they may have some tests there that might point you in the right direction

**Comment by AbhayAysola** [comment]
@zinoadidi I think this can be closed.
