### ISSUE TITLE
[Task] generateAccount function in Account manager uses JS SDK 

### ISSUE THREAD

**Issue by zinoadidi** [thenewboston-developers/thenewboston-js#98]
# Task

Contributors are able to complete this task and earn thenewboston coins.  Check out the labels to learn how much you can earn for contributing by completing this task.  Please make sure to be honest if you wish to contribute by saying you can't finish this and we can just un-assign you with no harm done!  There is no point in delaying tasks from being completed for miscommunication!

## Overview

generateAccount function in Account manager uses JS SDK 
- All missing functionalities that hinder the implementation are reported and resolved on the SDK side
- Use the [SDK documentation](https://github.com/thenewboston-developers/thenewboston-js/blob/development/docs/index.md)
- Undocumented processes and wrong information in doc should be corrected
- Resolves https://github.com/thenewboston-developers/Account-Manager/issues/585

## Behavior
Account manager uses js sdk installed from NPM https://www.npmjs.com/package/thenewboston
createBlock function in Account manager uses JS SDK 

```ts
/* code examples are awesome */
```

**Comment by AbhayAysola** [comment]
We can generate an account by just using `new tnb.Account()`

**Comment by tomijaga** [comment]
Shouldn't this be in the Account Manager Repo?

**Comment by zinoadidi** [comment]
@tomijaga to be honest i want to have them here for better management of the tasks; 
All tasks that are created here are just to help guild the process as I have agreed with Justin to take charge of the integration process. 
All small tasks here will be connected to the main task in the account manager repo https://github.com/thenewboston-developers/Account-Manager/issues/585 and will not generate any return from here;

The final bounty will be paid out as specified on the main task in the account manager

Here we can track the process of integration and make changes to SDK as needed when and if things arise during the integration process.

For instance, if during the switching you find a new method that is missing, then the PR for such method on SDK would reference this task or related task

**Comment by tomijaga** [comment]
Yh this makes sense

**Comment by zinoadidi** [comment]
@tomijaga i will work on publishing a new version to npm; 
Justin already made a dedicated branch for you to work from in the account manager repo.
Basically, we are ready when you are :)
Also, two new contributors will join our SDK team, let me know if you need some sort of assistance and we can work out something

**Comment by tomijaga** [comment]
@zinoadidi I'm ready. Can start working on it now.

**Comment by zinoadidi** [comment]
@tomijaga it's published. update me how it goes, what problems you face, etc

**Comment by tomijaga** [comment]
@zinoadidi Done with the account functions. Need to get the code reviewed and merge before i can move on to the next class

**Comment by zinoadidi** [comment]
All merge can go to the branch created for this integration task, let's get any one who is active on account manager repo to look at it and merge after. 

I would say once all work relating to account section is done, then we can look at getting Justin involve and see how we can get the updates to development branch. 

So we just do it batch by batch basically

**Comment by zinoadidi** [comment]
@tomijaga i looked at PR, seems you have done already all account-related things. Good job!

I guess we wait for Justin, not sure he will give us write access but i will leave a comment as well.

Will create the next set of tasks

**Comment by tomijaga** [comment]
Yh I hope he gives us access. It will make it faster. I can just push the changes and have him review when it's all done

**Comment by zinoadidi** [comment]
Tasks are now created;
will add some more tomorrow

you can filter issues / tasks relating to this project with `is:open is:issue project:thenewboston-developers/thenewboston-js/4 `

**Comment by tomijaga** [comment]
@zinoadidi I also found some functions that are missing from the sdk:
- getSingleBank
- getSingleValidator
- getSingleAccount
- updateValidatorTrust

I will create tasks for them

**Comment by zinoadidi** [comment]
@tomijaga it gets even better now;
So i will close all linked tasks as resolved, lets look towards the next steps;
Will try to download the version containing the changes you made and test it in my free time

**Comment by zinoadidi** [comment]
https://github.com/thenewboston-developers/Account-Manager/pull/609
